# Name of the GitHub Actions workflow
name: Deploy frontend

# The workflow is triggered on push or pull request to the main branch
on:
  push:
    branches:
      - CICD.v2  # This workflow gets triggered when changes are pushed to the main branch
  pull_request:
    branches:
      - CICD.v2  # This workflow also gets triggered on pull requests to the main branch

# Jobs to be executed in the workflow
jobs:

  # Second job to build, push, and deploy the Docker image
  build-push-deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on
    
    # Environmental variables used in this job
    env:
      AWS_REGION: us-east-1  # AWS region
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key ID
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret access key
      PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}  # Private SSH key for accessing the server
      SERVER_PUBLIC_IP: ${{ secrets.HOSTNAME }}  # Server's public IP address
      SERVER_USER_NAME: ${{ secrets.USER_NAME }}  # Username for the server

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE

      # This step builds the Docker image and pushes it to the Docker registry
      - name: Build and Push Docker Image
        run: |
          docker build -t levigab/job_listing-frontend:${GITHUB_SHA}  ./frontend  # Build the Docker image
          docker tag  levigab/job_listing-frontend:${GITHUB_SHA} levigab/job_listing-frontend:latest
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}  # Login to the Docker registry
          docker push levigab/job_listing-frontend:latest   # Push the image to the Docker registry

      # This step deploys the Docker image to the server
      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master  # This action allows executing SSH commands
        with:
          host: ${{ secrets.HOSTNAME }}  # The hostname of the server to deploy to
          username: ${{ secrets.USER_NAME }}  # The username to use for SSH
          key: ${{ secrets.AWS_SSH_KEY }}  # The SSH key to use
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION  # Environment variables to pass to the script
          script: |
            sudo systemctl restart docker  # Restart Docker on the server
            sleep 5  # Wait for 5 seconds
            sudo docker rm -f levigab/job_listing-frontend  # Remove the previous Docker container
            sudo docker rmi levigab/job_listing-frontend:latest   # Remove the previous Docker image
            sleep 5  # Wait for 5 seconds
            sudo docker run -d -p 3000:3000 levigab/job_listing-frontend:latest   # Run the new Docker image
            sudo docker ps  # List the running Docker containers

