# version: "3.1"
# version: "3.4"
version: "3.8"

x-airflow-common: &airflow-common
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.2.1}
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.1}
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.7.1}
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.1.1}
  build:
    context: ./airflow
    dockerfile: Dockerfile
  environment: &airflow-common-env
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    # AIRFLOW_CONN_MONGO_DEFAULT: mongodb://mongo:27017/${MONGO_DB_NAME}
    # AIRFLOW_CONN_JOBS_MONGODB: mongodb://mongo:27017/${MONGO_DB_NAME}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 30
    AIRFLOW__SMTP__SMTP_HOST: ${AIRFLOW__SMTP__SMTP_HOST}
    AIRFLOW__SMTP__SMTP_MAIL_FROM: ${AIRFLOW__SMTP__SMTP_MAIL_FROM}
    AIRFLOW__SMTP__SMTP_PASSWORD: ${AIRFLOW__SMTP__SMTP_PASSWORD}
    AIRFLOW__SMTP__SMTP_PORT: ${AIRFLOW__SMTP__SMTP_PORT}
    AIRFLOW__SMTP__SMTP_USER: ${AIRFLOW__SMTP__SMTP_USER}
    _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USERNAME}
    _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_PASSWORD}
    # _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- pymongo pandas requests bs4 langdetect airflow.providers.mongo}
    # _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- pymongo pandas requests bs4 langdetect}
    # AIRFLOW_CONN_MONGO_DEFAULT: mongo://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-rootpassword}@mongo:27017/%3FauthSource%3Dadmin
    # MONGO_URI: mongodb://mongo:27017/${MONGO_DB_NAME}
    # INTEGRATION_MONGO: true
  volumes:
    - ./airflow/config:/opt/airflow/config
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/data:/opt/airflow/data
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/ml:/opt/airflow/ml
    - ./airflow/plugins:/opt/airflow/plugins
    # - ./airflow/variables.json:/opt/airflow/variables.json
    # - ./airflow/init_scheduler.sh:/opt/airflow/init_scheduler.sh
    # - ./airflow/requirements.txt:/opt/airflow/requirements.txt
    # - ./airflow/config/airflow.cfg:/opt/airflow/airflow.cfg
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
    mongo:
      condition: service_healthy
  # profiles:
  #   - backend

services:
  api:
    # image: python:3.9-slim
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      # MONGO_URI: mongodb://mongo:27017/${MONGO_DB_NAME}
      MONGO_URI: mongodb://mongo:27017/
      MONGO_COLLECTION_ALL: ${MONGO_COLLECTION_ALL:-jobs_all}
      MONGO_DB_NAME: ${MONGO_DB_NAME:-job_listing_db}
    healthcheck:
      # test: [
      #     "CMD",
      #     "curl --fail http://0.0.0.0:8000/health || exit 1",
      #     # "curl --fail --cacert ./cert/cert.pem https://0.0.0.0:8000/health || exit 1",
      #   ]
      # test: ["CMD-SHELL", "wget --quiet --spider http://0.0.0.0:8000/health || exit 1"]
      # test: ["CMD-SHELL", "curl --fail http://0.0.0.0:8000/health || exit 1"]
      test: [
          "CMD-SHELL",
          # "curl --fail --cacert ./cert/cert.pem https://0.0.0.0:8000/health || exit 1",
          # "curl --fail --cacert ./backend/cert/cert.pem https://0.0.0.0:8000/health || exit 1",
          # "curl --cacert ./backend/cert/cert.pem https://1270.0.0.1:443/health || exit 1",
          "curl --fail http://0.0.0.0:8000/health || exit 1",
        ]
      # test:
      #   [
      #     "CMD-SHELL",
      #     "wget --no-verbose --tries=1 http://0.0.0.0:8000/health || exit 1",
      #   ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    # profiles:
    #   - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-rootpassword}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MAIN_COLLECTION_NAME: ${MONGO_COLLECTION_ALL}
      INDEX_FIELD: url
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "db.runCommand('ping').ok",
          "|",
          "mongosh",
          "localhost:27017/test",
          "--quiet",
        ]
      interval: 5s
      timeout: 30s
      retries: 30
      start_period: 40s
    # profiles:
    #   - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/src
    depends_on:
      mongo:
        condition: service_healthy
      api:
        condition: service_healthy
    # profiles:
    #   - frontend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    # profiles:
    #   - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    # profiles:
    #   - backend

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    # command: bash -c "pip install -r /opt/airflow/requirements.txt && airflow scheduler"
    # command: /bin/bash -c "/opt/airflow/init_scheduler.sh"
    # command: bash -c "/opt/airflow/init_scheduler.sh"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"',
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    ports:
      - 8793:8793
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    # command: version
    # command: bash -c "airflow variables import /opt/airflow/variables.json && airflow version"
    command: bash -c "/opt/airflow/config/airflow_init.sh"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "false"
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_PASSWORD:-airflow}
      _AIRFLOW_WWW_USER_EMAIL: ${AIRFLOW_WWW_EMAIL:-someemail@gmail.com}

  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - 5555:5555
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

# networks:
#   default:
#     external: true
#     driver: bridge
# app-network:
#   name: jobs-app-network
#   external: true
#   driver: bridge

volumes:
  mongo-data:
  postgres-db-volume:
