dimensions_info:
 dimSources:
  factColumn: "source"
  dimColumn: "name"
  distinctColumns: ["name"]
  factForeignKeyColumn: "sourceKey"
  dimIdColumn: ""
 dimCompanies:
  factColumn: "company_name"
  dimColumn: "name"
  distinctColumns: ["name"]
  factForeignKeyColumn: "CompanyKey"
  dimIdColumn: ""
 dimLanguages:
  factColumn: "language"
  dimColumn: "name"
  distinctColumns: ["name"]
  factForeignKeyColumn: "LanguageKey"
  dimIdColumn: ""
 dimJobLevels:
  factColumn: "level"
  dimColumn: "name"
  distinctColumns: ["name"]
  factForeignKeyColumn: "JobLevelKey"
  dimIdColumn: ""
