# FROM apache/airflow:2.1.1
FROM apache/airflow:2.7.2
COPY requirements.txt .
# RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt
RUN pip install --no-cache-dir -r requirements.txt