dimensions_info:
 dimJobs:
  factColumns: "fingerprint"
  dimColumns: "fingerprint"
  distinctColumns: ["fingerprint"]
  # factForeignKeyColumns: "job_key"
 dimCompanies:
  factColumns: "company_name"
  dimColumns: "name"
  distinctColumns: ["name"]
  # factForeignKeyColumns: "company_key"
 dimLocations:
  factColumns: "location"
  dimColumns: "city"
  distinctColumns: ["city"]
  # factForeignKeyColumns: "location_key"
 dimLanguages:
  factColumns: "language"
  dimColumns: "name"
  distinctColumns: ["name"]
  # factForeignKeyColumns: "language_key"
 dimSources:
  factColumns: "source"
  dimColumns: "name"
  distinctColumns: ["name"]
  # factForeignKeyColumns: "source_key"
 dimJobLevels:
  factColumns: "level"
  dimColumns: "name"
  distinctColumns: ["name"]
  # factForeignKeyColumns: "job_level_key"
 # dimSearchKeywords:
 #  factColumns: "level"
 #  dimColumns: "name"
 #  distinctColumns: ["name"]
 # factForeignKeyColumns: "job_level_key"
 # dimSearchLocations:
 #  factColumns: "search_location"
 #  dimColumns: "name"
 #  distinctColumns: ["name"]
 # factForeignKeyColumns: "job_level_key"
 dimDates:
  factColumns: ["publish_date_unique", "search_datetime_unique"]
  dimColumns: "date_unique"
  distinctColumns: ["date_unique"]
  factForeignKeyColumns: ["search_date_key", "publish_date_key"]
 dimEmployments:
  factColumns: ["employment"]
  dimColumns: "name"
  distinctColumns: ["name"]
  # factForeignKeyColumns: ["employment_key"]
 dimIndustries:
  factColumns: ["industries"]
  dimColumns: "name"
  distinctColumns: ["name"]
  # factForeignKeyColumns: ["industry_key"]

fact_info:
 fctJobListings:
  dimKeyColumns:
   [
    "job_key",
    "company_key",
    "source_key",
    "search_date_key",
    "publish_date_key",
    "close_date_key",
    "language_key",
    "job_level_key",
    "employment_key",
    "industry_key",
   ]
  otherColumns: ["job_apps_count", "list_dur_days", "scrape_dur_ms"]

bridge_info:
 JobSkillsBridge:
  someValue: "empty"
 JobTechnologiesBridge:
  someValue: "empty"
 JobSearchKeywordBridge:
  someValue: "empty"
 JobSearchLocationBridge:
  someValue: "empty"
