dimensions_info:
 dimJobs:
  factColumns: "title"
  dimColumns: "title"
  uniqueColumns: ["fingerprint"]
  # factForeignKeyColumns: "job_key"
 dimCompanies:
  factColumns: "company_name"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "company_key"
 dimSourceInfos:
  factColumns: "url"
  dimColumns: "url"
  uniqueColumns: ["url"]
  isBridge: true
  # factForeignKeyColumns: "source_info_key"
 dimLocations:
  factColumns: "location"
  dimColumns: "city"
  uniqueColumns: ["city"]
  # factForeignKeyColumns: "location_key"
 dimIndustries:
  factColumns: "industries"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "location_key"
 dimLanguages:
  factColumns: "language"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "language_key"
 dimSources:
  factColumns: "source"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # isBridge: true
  # factForeignKeyColumns: "source_key"
 dimJobLevels:
  factColumns: "level"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "job_level_key"
 dimSearchKeywords:
  factColumns: "search_keyword"
  dimColumns: "name"
  uniqueColumns: ["name"]
  isBridge: true
 # factForeignKeyColumns: "job_level_key"
 dimSearchLocations:
  factColumns: "search_location"
  dimColumns: "name"
  uniqueColumns: ["name"]
  isBridge: true
 # factForeignKeyColumns: "job_level_key"
 dimDates:
  factColumns: ["publish_date_unique", "search_datetime_unique"]
  dimColumns: "date_unique"
  uniqueColumns: ["date_unique"]
  factForeignKeyColumns: ["search_date_key", "publish_date_key"]
 dimEmployments:
  factColumns: ["employment"]
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: ["employment_key"]

fct_info:
 fctJobListings:
  dimKeyColumns: [
    "job_key",
    "company_key",
    "source_key",
    "search_date_key",
    "publish_date_key",
    # "close_date_key",
    "language_key",
    "job_level_key",
    "employment_key",
   ]
  otherColumns:
   ["job_apps_count", "list_dur_days", "scrape_dur_ms", "fingerprint"]
  bridgeColumns: [
    "industry_key",
    "source_info_key",
    "search_keyword_key",
    "search_location_key",
    # "skill_key",
    # "technology_key",
   ]

  uniqueColumns: ["fingerprint"]

bridge_info:
 JobSkillsBridge:
  fctKeyColumn: "empty"
 JobTechnologiesBridge:
  fctKeyColumn: "empty"
 JobSearchKeywordBridge:
  fctKeyColumn: "empty"
 JobSearchLocationBridge:
  fctKeyColumn: "empty"
 JobSourceInfoBridge:
  fctKeyColumn: "empty"
