dimensions_info:
 dimJobs:
  factColumns: "title"
  dimColumns: "title"
  uniqueColumns: ["fingerprint"]
  # factForeignKeyColumns: "job_key"
 dimCompanies:
  factColumns: "company_name"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "company_key"
 dimSourceInfos:
  factColumns: "url"
  dimColumns: "url"
  uniqueColumns: ["url"]
  # factForeignKeyColumns: "source_info_key"
 dimLocations:
  factColumns: "location"
  dimColumns: "city"
  uniqueColumns: ["city"]
  # factForeignKeyColumns: "location_key"
 dimLanguages:
  factColumns: "language"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "language_key"
 dimSources:
  factColumns: "source"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "source_key"
 dimJobLevels:
  factColumns: "level"
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: "job_level_key"
 # dimSearchKeywords:
 #  factColumns: "level"
 #  dimColumns: "name"
 #  uniqueColumns: ["name"]
 # factForeignKeyColumns: "job_level_key"
 # dimSearchLocations:
 #  factColumns: "search_location"
 #  dimColumns: "name"
 #  uniqueColumns: ["name"]
 # factForeignKeyColumns: "job_level_key"
 dimDates:
  factColumns: ["publish_date_unique", "search_datetime_unique"]
  dimColumns: "date_unique"
  uniqueColumns: ["date_unique"]
  factForeignKeyColumns: ["search_date_key", "publish_date_key"]
 dimEmployments:
  factColumns: ["employment"]
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: ["employment_key"]
 dimIndustries:
  factColumns: ["industries"]
  dimColumns: "name"
  uniqueColumns: ["name"]
  # factForeignKeyColumns: ["industry_key"]

fact_info:
 fctJobListings:
  dimKeyColumns: [
    "job_key",
    "company_key",
    "source_key",
    "search_date_key",
    "publish_date_key",
    # "close_date_key",
    "language_key",
    "job_level_key",
    "employment_key",
    # "industry_key",
   ]
  otherColumns: [
    "job_apps_count",
    # "list_dur_days",
    "scrape_dur_ms",
    "fingerprint",
   ]
  uniqueColumns: ["fingerprint"]

bridge_info:
 JobSkillsBridge:
  someValue: "empty"
 JobTechnologiesBridge:
  someValue: "empty"
 JobSearchKeywordBridge:
  someValue: "empty"
 JobSearchLocationBridge:
  someValue: "empty"
 JobSourceInfoBridge:
  someValue: "empty"
