action_id: trunk-share-with-everyone
date: 2023-09-04 10:54:35
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1693824875
full_timestamp:
  nanos: 232112000
  seconds: 1693824875
trunk_version: 1.14.2
