name: Deploy MongoDB

on:
  push:
    branches:
      - CICD.v2

jobs:
  build-push-deploy-mongo:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
      SERVER_PUBLIC_IP: ${{ secrets.HOSTNAME }}
      SERVER_USER_NAME: ${{ secrets.USER_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push MongoDB Image
        run: |
          docker build -t mongo:${GITHUB_SHA}
          docker tag mongo:${GITHUB_SHA} mongo:latest
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}
          docker push mongo:latest

      - name: Deploy MongoDB Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
          script: |
            sudo systemctl restart docker
            sleep 5
            sudo docker rm -f mongo
            sudo docker rmi mongo:latest
            sleep 5
            sudo docker run -d -p 27017:27017 \
              -e MONGO_INITDB_DATABASE=${MONGO_DB_NAME} \
              -e MAIN_COLLECTION_NAME=${MONGO_COLLECTION_ALL} \
              -e INDEX_FIELD=url \
              mongo:latest
            sudo docker ps
