# Name of the GitHub Actions workflow
name: Deploy frontend

# The workflow is triggered on push or pull request to the main branch
on:
  push:
    branches:
      - CICD.v2  # This workflow gets triggered when changes are pushed to the main branch
  pull_request:
    branches:
      - CICD.v2  # This workflow also gets triggered on pull requests to the main branch

# Jobs to be executed in the workflow
jobs:

  # Second job to build, push, and deploy the Docker image
  build-push-deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on
    
    # Environmental variables used in this job
    env:
      AWS_REGION: us-east-1  # AWS region
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key ID
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret access key
      PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}  # Private SSH key for accessing the server
      SERVER_PUBLIC_IP: ${{ secrets.HOSTNAME }}  # Server's public IP address
      SERVER_USER_NAME: ${{ secrets.USER_NAME }}  # Username for the server

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE

      # This step builds the Docker image and pushes it to the Docker registry
      - name: Build and Push Docker Image
        run: |
          docker build -t levigab/job_listing-frontend:${GITHUB_SHA}  ./frontend  # Build the Docker image
          docker tag  levigab/job_listing-frontend:${GITHUB_SHA} levigab/job_listing-frontend:latest
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}  # Login to the Docker registry
          docker push levigab/job_listing-frontend:latest   # Push the image to the Docker registry


