name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies and Run Unit Tests
        run: |
          pip3 install pytest mongomock pymongo fastapi httpx
          cd backend/tests
          pytest

  build-push-deploy:
    runs-on: ubuntu-latest
    needs: unit-test
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
      SERVER_PUBLIC_IP: ${{ secrets.HOSTNAME }}
      SERVER_USER_NAME: ${{ secrets.USER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          # Build and push the Docker image
          docker build -t levigab/job_listing-api:latest-Deploy-v2 ./backend
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}
          docker push levigab/job_listing-api:latest-Deploy-v2

      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
          script: |
            # Restart Docker, remove previous containers/images, and run the new image
            sudo systemctl restart docker
            sleep 5
            sudo docker rm -f fastapi
            sudo docker rmi levigab/job_listing-api:latest-Deploy-v2
            sleep 5
            sudo docker run -d -p 8000:8000 levigab/job_listing-api:latest-Deploy-v2
            sudo docker ps
